dataProject/myproject/main_page/urls.py
from django.urls import path
from . import views
from registration.views import register,login_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('income/', views.income_list, name='income_list'),
    path('add_income/', views.add_income, name='add_income'),
    path('expense/', views.expense_list, name='expense_list'),
    path('add_expense/', views.add_expense, name='add_expense'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('home/', views.home_view, name='home'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('graph_income/', views.graph_income, name='graph_income'),
    path('graph_expense/', views.graph_expense, name='graph_expense'),
    path('compare/', views.compare_income_expense, name='compare'),
    path('send_email/', views.send_email, name='email_form'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dataProject/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='unique_admin_name'),
    path('', include('main_page.urls')),
]

   

dataProject/myproject/main_page/models.py
from django.db import models
from django.contrib.auth.models import User

CURRENCY_CHOICES = [
    ('USD', 'USD'),
    ('EUR', 'EUR'),
    ('GBP', 'GBP'),
]

PAYMENT_METHOD_CHOICES = [
    ('Cash', 'Cash'),
    ('Credit Card', 'Credit Card'),
    ('Bank Transfer', 'Bank Transfer'),
]

CATEGORY_CHOICES_INCOME = [
    ('Work1', 'Work 1'),
    ('Work2', 'Work 2'),
    ('Work3', 'Work 3'),
    ('Foreign_income', 'Foreign Income'),
    ('Investments', 'Investments'),
]

CATEGORY_CHOICES_EXPENSE = [
    ('Fod', 'Food'),
    ('Clothes', 'Clothes'),
    ('Rent', 'Rent'),
    ('Another_expenses', 'Another Expenses'),
]


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Income(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(
        max_length=50, default='', choices=CURRENCY_CHOICES)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    custom_category = models.CharField(max_length=50, blank=True)

    def get_category_display(self):
        if self.custom_category:
            return self.custom_category
        return dict(CATEGORY_CHOICES_INCOME).get(self.category)


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(
        max_length=50, default='', choices=CURRENCY_CHOICES)
    payment_method = models.CharField(
        max_length=50, choices=PAYMENT_METHOD_CHOICES)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    custom_category = models.CharField(max_length=50, blank=True)

    def get_category_display(self):
        if self.custom_category:
            return self.custom_category
        return dict(CATEGORY_CHOICES_EXPENSE).get(self.category)

dataProject/myproject/main_page/forms.py
from django import forms
from .models import Income, Expense, Category, CATEGORY_CHOICES_INCOME, CATEGORY_CHOICES_EXPENSE


class IncomeForm(forms.ModelForm):
    category_name = forms.ChoiceField(choices=CATEGORY_CHOICES_INCOME)
    custom_category = forms.CharField(max_length=50, required=False)

    class Meta:
        model = Income
        fields = ['date', 'amount', 'currency']
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker', 
                                           'autocomplete': 'off', 
                                           'id': 'income_date'}
                                    )
                }

    def __init__(self, *args, **kwargs):
        kwargs.pop('user', None)
        super(IncomeForm, self).__init__(*args, **kwargs)


class ExpenseForm(forms.ModelForm):
    category_name = forms.ChoiceField(choices=CATEGORY_CHOICES_EXPENSE)
    custom_category = forms.CharField(max_length=50, required=False)

    class Meta:
        model = Expense
        fields = ['date', 'amount', 'currency', 'payment_method']
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker', 
                                           'autocomplete': 'off', 
                                           'id': 'expense_date'}
                                    )
                }

    def __init__(self, *args, **kwargs):
        kwargs.pop('user', None)
        super(ExpenseForm, self).__init__(*args, **kwargs)


class EmailForm(forms.Form):
    to = forms.EmailField()

dataProject/myproject/main_page/views.py
from io import StringIO
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from decouple import config
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from .forms import IncomeForm, ExpenseForm, EmailForm
from .graph import plot_histogram, line_graph, pie_chart, chart_bar, compare
from .utils import convert_set_to_csv, convert_to_csv, process_category
from .models import Income, Expense, Category


def send_email(request):
    if request.method == "POST":
        form = EmailForm(request.POST)

        if form.is_valid():
            recipient_email = form.cleaned_data["to"]
            incomes = Income.objects.filter(user=request.user)
            fieldnames = ['date', 'amount', 'currency']
            csv_data1 = convert_set_to_csv(incomes, fieldnames)

            expenses = Expense.objects.filter(user=request.user)
            fieldnames = ['date', 'amount', 'currency', 'payment_method']
            csv_data2 = convert_set_to_csv(expenses, fieldnames)

            email = EmailMessage(
                "Financial report",
                "Hello,\n\nHere is your financial report.",
                config('EMAIL_HOST_USER')  , 
                [recipient_email], 
            )
            email.attach("income_report.csv", csv_data1, "text/csv")
            email.attach("expense_report.csv", csv_data2, "text/csv")

            email.send()

            return redirect('home')
    else:
        form = EmailForm()
    return render(request, "email_form.html", {"form": form})


@login_required
def graph_income(request):
    incomes = Income.objects.filter(user=request.user)
    fieldnames = ['date', 'amount', 'currency', 'category_id']
    csv_filename = convert_to_csv(incomes, fieldnames)

    df = pd.read_csv(csv_filename)

    # line
    fig = line_graph(df, 'date', 'amount')

    graph_filename = os.path.join('static', 'income_graph.png')
    plt.savefig(graph_filename)
    plt.close(fig)

    # pie chart
    grouped_data = df.groupby('category_id')['amount'].sum()
    category_ids = grouped_data.index.tolist()
    amounts = grouped_data.tolist()

    categories = Category.objects.filter(id__in=category_ids)
    labels = [str(category) for category in categories]

    fig = pie_chart(amounts, labels)
    graph_filename2 = os.path.join('static', 'income_equal.png')
    plt.savefig(graph_filename2)
    plt.close(fig)

    # chart_bar for currency
    currency_counts = df['currency'].value_counts()
    fig = chart_bar(currency_counts)
    graph_filename3 = os.path.join('static', 'income_bar_chart.png')
    plt.savefig(graph_filename3)
    plt.close(fig)

    #heatmap
    df['date'] = pd.to_datetime(df['date']) 
    df['month'] = df['date'].dt.month 
    df['year'] = df['date'].dt.year  
    df_grouped = df.groupby(['year', 'month'])['amount'].sum().reset_index()

    df_pivot = df_grouped.pivot('month', 'year', 'amount')

    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(data=df_pivot, annot=True, fmt=".1f", cmap='viridis', ax=ax)

    ax.set_xlabel('Year')
    ax.set_ylabel('Month')
    ax.set_title('Income Heatmap')
    ax.invert_yaxis()

    graph_filename4 = 'static/heatmap.png'
    plt.savefig(graph_filename4)
    plt.close(fig)

    context = {
        'csv_filename': csv_filename,
        'graph_filename': graph_filename,
        'graph_filename2': graph_filename2,
        'graph_filename3': graph_filename3,
        'graph_filename4': graph_filename4
    }
    return render(request, 'graph_income.html', context)


@login_required
def graph_expense(request):
    expenses = Expense.objects.filter(user=request.user)
    fieldnames = ['date', 'amount', 'currency',
                  'payment_method', 'category_id']
    csv_filename = convert_to_csv(expenses, fieldnames)

    df = pd.read_csv(csv_filename)

    # line
    fig = line_graph(df, 'date', 'amount')

    graph_filename = os.path.join('static', 'expense_graph.png')
    plt.savefig(graph_filename)
    plt.close(fig)

    # hist for amount
    fig = plot_histogram(df, 'amount')
    graph_filename1 = os.path.join('static', 'expense_amount_histogram.png')
    plt.savefig(graph_filename1)
    plt.tight_layout()
    plt.close(fig)

    # chart_bar for payment
    payment_counts = df['payment_method'].value_counts()
    fig = chart_bar(payment_counts)
    graph_filename2 = os.path.join('static', 'expense_bar_chart.png')
    plt.savefig(graph_filename2)
    plt.tight_layout()
    plt.close(fig)

    # pie chart
    grouped_data = df.groupby('category_id')['amount'].sum()
    category_ids = grouped_data.index.tolist()
    amounts = grouped_data.tolist()

    categories = Category.objects.filter(id__in=category_ids)
    labels = [str(category) for category in categories]

    fig = pie_chart(amounts, labels)
    graph_filename3 = os.path.join('static', 'expense_equal.png')
    plt.savefig(graph_filename3)
    plt.close(fig)

    #heatmap
    df['date'] = pd.to_datetime(df['date']) 
    df['month'] = df['date'].dt.month 
    df['year'] = df['date'].dt.year  
    df_grouped = df.groupby(['year', 'month'])['amount'].sum().reset_index()

    df_pivot = df_grouped.pivot('month', 'year', 'amount')

    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(data=df_pivot, annot=True, fmt=".1f", cmap='viridis', ax=ax)

    ax.set_xlabel('Year')
    ax.set_ylabel('Month')
    ax.set_title('Expense Heatmap')
    ax.invert_yaxis()
    
    graph_filename4 = 'static/heatmap_expense.png'
    plt.savefig(graph_filename4)
    plt.close(fig)

    context = {
        'csv_filename': csv_filename,
        'graph_filename': graph_filename,
        'graph_filename1': graph_filename1,
        'graph_filename2': graph_filename2,
        'graph_filename3': graph_filename3,
        'graph_filename4': graph_filename4
    }

    return render(request, 'graph_expense.html', context)


@login_required
def compare_income_expense(request):
    incomes = Income.objects.filter(user=request.user)
    fieldnames = ['date', 'amount', 'currency', 'category_id']
    csv_data1 = convert_set_to_csv(incomes, fieldnames)

    expenses = Expense.objects.filter(user=request.user)
    fieldnames = ['date', 'amount', 'currency',
                  'payment_method', 'category_id']
    csv_data2 = convert_set_to_csv(expenses, fieldnames)

    df1 = pd.read_csv(StringIO(csv_data1))
    df2 = pd.read_csv(StringIO(csv_data2))
    income_sum = df1['amount'].sum()
    expense_sum = df2['amount'].sum()
    # print(income_sum)
    # print(expense_sum)
    data = {'Type': ['Income', 'Expense'], 'Amount': [income_sum, expense_sum]}
    df = pd.DataFrame(data)

    # compareBarChart
    fig = compare(data=df, x='Type', y='Amount')
    graph_filename = os.path.join('static', 'compare.png')
    plt.savefig(graph_filename)
    plt.close(fig)

    context = {'graph_filename': graph_filename}

    return render(request, 'compare.html', context)


@login_required
def home_view(request):
    username = request.user.username
    return render(request, 'home.html', {'username': username})


@login_required
def income_list(request):
    incomes = Income.objects.filter(user=request.user)
    categories = Category.objects.filter(income__in=incomes).distinct()

    if request.method == 'POST' and 'delete' in request.POST:
        income_id = request.POST.get('delete')
        income = Income.objects.get(id=income_id)
        income.delete()
        return redirect('income_list')

    context = {
        'incomes': incomes,
        'categories': categories,
    }
    return render(request, 'income_list.html', context)


@login_required
def expense_list(request):
    expenses = Expense.objects.filter(user=request.user)
    categories = Category.objects.filter(expense__in=expenses)

    if request.method == 'POST' and 'delete' in request.POST:
        expense_id = request.POST.get('delete')
        expense = Expense.objects.get(id=expense_id)
        expense.delete()
        return redirect('expense_list')

    context = {
        'expenses': expenses,
        'categories': categories,
    }
    return render(request, 'expense_list.html', context)


@login_required
def add_income(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST, user=request.user)

        if form.is_valid():
            category_name = form.cleaned_data['category_name']
            custom_category = form.cleaned_data['custom_category']
            category = process_category(
                category_name, custom_category, request.user)
            form.instance.user = request.user
            form.instance.category = category
            form.instance.custom_category = custom_category
            form.save()
            return redirect('add_income')

    else:
        form = IncomeForm(user=request.user)
    return render(request, 'add_income.html', {'form': form})


@login_required
def add_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST, user=request.user)

        if form.is_valid():
            category_name = form.cleaned_data['category_name']
            custom_category = form.cleaned_data['custom_category']
            category = process_category(
                category_name, custom_category, request.user)
            form.instance.user = request.user
            form.instance.category = category
            form.instance.custom_category = custom_category
            form.save()
            return redirect('add_expense')

    else:
        form = ExpenseForm(user=request.user)
    return render(request, 'add_expense.html', {'form': form})

dataProject/myproject/main_page/templates/add_expense.html
<!DOCTYPE html>
<html>
<head>
    <h1 class="text-center">Add your expense here</h1>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
        <style>
        body {
            padding: 20px;
        }
        h1 {
            margin-bottom: 20px;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
        }
        .button-group {
            display: flex;
            justify-content: center;
            margin-top: 10px;
        }
        .button-group .btn {
            margin: 0 5px;
            flex: 1;
        }
    </style>
</head>
<body>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="button-group">
        <button type="submit" class="btn btn-primary">Add</button>
        <a class="btn btn-primary" href="{% url 'expense_list' %}">Get expense List</a>
        <a class="btn btn-primary" href="{% url 'home' %}">Back to home</a>
    </div>
    </form>
</body>
</html>

dataProject/myproject/main_page/templates/add_income.html
<!DOCTYPE html>
<html>
<head>
    <h1 class="text-center">Add your income here</h1>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
            <style>
        body {
            padding: 20px;
        }
        h1 {
            margin-bottom: 20px;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
        }
        .button-group {
            display: flex;
            justify-content: center;
            margin-top: 10px;
        }
        .button-group .btn {
            margin: 0 5px;
            flex: 1;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
    <div class="button-group">
        <button  type="submit" class="btn btn-primary">Add</button>
        <a class="btn btn-primary" href="{% url 'income_list' %}">Get Income List</a>
        <a class="btn btn-primary" href="{% url 'home' %}">Back to home</a>
    </div>
    </form>
</body>
</html>

dataProject/myproject/main_page/templates/compare.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Compare analysis</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
    <h2 class="text-center">Compare</h2>
    <div class="text-center">
      <img src="{% static 'compare.png' %}" alt="Compare">
    </div>
  </div>
</body>
</html>

dataProject/myproject/main_page/templates/email_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Send financial report</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        body {
            padding: 20px;
        }
        h1 {
            margin-bottom: 20px;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
        }
        .button-group {
            display: flex;
            justify-content: center;
            margin-top: 10px;
        }
        .button-group button {
            margin: 0 5px;
            flex: 1;
        }
    </style>
</head>
<body>
    <h1 class="text-center">Send financial report to your email here</h1>
    <form method="post" action="{% url 'email_form' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_to" class="form-label">To:</label>
            <input type="email" class="form-control" id="id_to" name="to" required>
        </div>
        <div class="button-group">
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>
</body>
</html>

dataProject/myproject/main_page/templates/expense_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Expense List</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
       <style>
        body {
            padding: 20px;
        }
        h1 {
            margin-bottom: 20px;
        }
    </style>
</head>
<body> 
<div class="container-fluid">
        <h1 class="text-center">Expense List</h1>
    
     <form method="POST" action="{% url 'expense_list' %}">
        {% csrf_token %}
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Payment Method</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expenses %}
                <tr>
                    <td>{{ expense.date }}</td>
                    <td>{{ expense.amount }}</td>
                    <td>{{ expense.currency }}</td>
                    <td>{{ expense.payment_method }}</td>
                    <td>{{ expense.category.name }}</td>
                    <td>
                        <button type="submit" name="delete" value="{{ expense.id }}" class="btn btn-danger">Delete</button>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No expenses available</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
  <div class="text-center">
    <a class = "btn btn-primary " href="{% url 'add_expense' %}">Add Expense</a>
    <a class = "btn btn-primary " href="{% url 'home' %}">Back</a>
    <a class = "btn btn-primary " href="{% url 'graph_expense' %}">Get analysis</a>
    <a class = "btn btn-primary " href="{% url 'email_form' %}">Send analysis by email</a>
  </div>
</div>
</body>
</html>

dataProject/myproject/main_page/templates/graph_expense.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Expense analysis</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
    <h2 class="text-center">Expense histogram</h2>
    <div class="text-center">
      <img src="{% static 'expense_amount_histogram.png' %}" alt="Expense Amount Histogram">
    </div>
    <h2 class="text-center">Expense bar chart</h2>
    <div class="text-center">
      <img src="{% static 'expense_bar_chart.png' %}" alt="Expense Bar Chart">
    </div>
    <h2 class="text-center">Expense line graph</h2>
    <div class="text-center">
      <img src="{% static 'expense_graph.png' %}" alt="Expense Line Graph">
    </div>
    <h2 class="text-center">Expense pie chart</h2>
    <div class="text-center">
      <img src="{% static 'expense_equal.png' %}" alt="Expense equal">
    </div>
     <h2 class="text-center">Heatmap</h2>
    <div class="text-center">
      <img src="{% static 'heatmap_expense.png' %}" alt="Heatmap">
    </div>
  </div>
</body>
</html>

dataProject/myproject/main_page/templates/graph_income.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Income analysis</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
 <div class="container">
    <h2 class="text-center">Income line graph</h2>
    <div class="text-center">
      <img src="{% static 'income_graph.png' %}" alt="Income Graph">
    </div>

    <h2 class="text-center">Income pie chart</h2>
    <div class="text-center">
      <img src="{% static 'income_equal.png' %}" alt="Income Graph">
    </div>

    <h2 class="text-center">Income bar chart</h2>
    <div class="text-center">
      <img src="{% static 'income_bar_chart.png' %}" alt="Income Graph">
    </div>
     <h2 class="text-center">Heatmap</h2>
    <div class="text-center">
      <img src="{% static 'heatmap.png' %}" alt="Heatmap">
    </div>
  </div>
</body>
</html>

dataProject/myproject/main_page/templates/home.html
<div class="container">
<h2>Welcome, {{ username }}</h2>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<a class = "btn btn-primary " href="{% url 'logout' %}">Logout</a>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Get options
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class = "dropdown-item" href="{% url 'add_income' %}">Add Income</a></li>
    <li><a class = "dropdown-item" href="{% url 'add_expense' %}">Add Expense</a></li>
    <li><a class = "dropdown-item" href="{% url 'income_list' %}">View my income list</a></li>
    <li><a class = "dropdown-item" href="{% url 'expense_list' %}">View my expense list</a></li>
    <li><a class = "dropdown-item" href="{% url 'graph_income' %}">Get income analysis</a></li>
    <li><a class = "dropdown-item" href="{% url 'graph_expense' %}">Get expense analysis</a></li>
    <li><a class = "dropdown-item" href="{% url 'compare' %}">Get compare analysis</a></li>
  </ul>
</div>
</div>
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }

    .logout-button {
        align-self: flex-end;
    }
</style>

dataProject/myproject/main_page/templates/income_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Income List</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
          <style>
        body {
            padding: 20px;
        }
        h1 {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <h1 class="text-center">Income List</h1>
        <form method="POST" action="{% url 'income_list' %}">
        {% csrf_token %}
       <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            {% for income in incomes %}
                <tr>
                    <td>{{ income.date }}</td>
                    <td>{{ income.amount }}</td>
                    <td>{{ income.currency }}</td>
                    <td>{{ income.category.name }}</td>
              
                    <td>
                        <button type="submit" name="delete" value="{{ income.id }}" class="btn btn-danger">Delete</button>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No incomes available</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
  <div class="text-center">
    <a class = "btn btn-primary " href="{% url 'add_income' %}">Add Income</a>
    <a class = "btn btn-primary " href="{% url 'home' %}">Back</a>
    <a class = "btn btn-primary " href="{% url 'graph_income' %}">Get analysis</a>
    <a class = "btn btn-primary " href="{% url 'email_form' %}">Send analysis by email</a>
  </div>
</div>
</body>
</html>